version: '3.8'
services:
  restapi:
    image: node:16-bullseye
    working_dir: /app
    container_name: restapi
    entrypoint:
      ['/bin/bash', '-c', 'npm install && npm run start']
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ${PWD}:/app/
    links:
      - mongo
    environment:
      - URL_MONGO=mongodb://api:docker1234@mongo
  mongo:
    image: mongo
    volumes:
      - "./mongo/data:/data/db"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=api
      - MONGO_INITDB_ROOT_PASSWORD=docker1234
